### ISSUE TITLE
.ssh directory permissions

### ISSUE THREAD

**Issue by cjcopi** [cwru-pat/ssh_keys_how_to#1]
I don't like the idea of creating .ssh as the user and using those default permissions.  It is probably best to ssh somewhere first (even if you do not login) so that ssh can create this directory itself.

If you are going to create it yourself I would set the permissions to something restrictive,
probably 0700 :
> chmod 0700 ~/.ssh

**Comment by deskinsjt** [comment]
Thats fair. I had never needed to create the directory myself. I will add this and close.
